# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videosave.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 937)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startbtn = QtWidgets.QPushButton(self.centralwidget)
        self.startbtn.setGeometry(QtCore.QRect(380, 10, 89, 25))
        self.startbtn.setObjectName("startbtn")
        self.recivebtn = QtWidgets.QPushButton(self.centralwidget)
        self.recivebtn.setGeometry(QtCore.QRect(490, 10, 89, 25))
        self.recivebtn.setObjectName("recivebtn")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(40, 40, 911, 711))
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setText("")
        self.image.setObjectName("image")
        self.sshiptext = QtWidgets.QLineEdit(self.centralwidget)
        self.sshiptext.setGeometry(QtCore.QRect(80, 10, 181, 25))
        self.sshiptext.setObjectName("sshiptext")
        self.sshbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sshbutton.setGeometry(QtCore.QRect(270, 10, 89, 25))
        self.sshbutton.setObjectName("sshbutton")
        self.msgbox = QtWidgets.QTextEdit(self.centralwidget)
        self.msgbox.setGeometry(QtCore.QRect(60, 780, 671, 70))
        self.msgbox.setFrameShape(QtWidgets.QFrame.Box)
        self.msgbox.setObjectName("msgbox")
        self.exitbtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitbtn.setGeometry(QtCore.QRect(610, 10, 89, 25))
        self.exitbtn.setObjectName("exitbtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startbtn.setText(_translate("MainWindow", "开始"))
        self.recivebtn.setText(_translate("MainWindow", "接收"))
        self.sshiptext.setPlaceholderText(_translate("MainWindow", "请输入服务器ip"))
        self.sshbutton.setText(_translate("MainWindow", "ssh连接"))
        self.exitbtn.setText(_translate("MainWindow", "退出"))
